package com.nojoum.al.malaeb;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

import com.nojoum.al.malaeb.dao.CountryRepository;
import com.nojoum.al.malaeb.dao.MemberRepository;
import com.nojoum.al.malaeb.entiies.Country;
import com.nojoum.al.malaeb.entiies.Membre;



@SpringBootApplication
public class RegFormeApplication  {
	//@Autowired
	//private CountryRepository countryRepository;
	public static void main(String[] args) {
		//SpringApplication.run(RegFormeApplication.class, args);
		ApplicationContext ctx =SpringApplication.run(RegFormeApplication.class, args);
		CountryRepository countryRepository=ctx.getBean(CountryRepository.class);
		countryRepository.save(new Country("Afghanistan"));
		countryRepository.save(new Country("Albania"));
		countryRepository.save(new Country("Algeria"));
		countryRepository.save(new Country("American Samoa"));
		countryRepository.save(new Country("Andorra"));
		countryRepository.save(new Country("Angola"));
		countryRepository.save(new Country("Anguilla"));
		countryRepository.save(new Country("Antarctica"));
		countryRepository.save(new Country("Antigua and Barbuda"));
		countryRepository.save(new Country("Argentina"));
		countryRepository.save(new Country("Armenia"));
		countryRepository.save(new Country("Aruba"));
		countryRepository.save(new Country("Australia"));
		countryRepository.save(new Country("Austria"));
		countryRepository.save(new Country("Azerbaijan"));
		countryRepository.save(new Country("Bahamas"));
		countryRepository.save(new Country("Bahrain"));
		countryRepository.save(new Country("Bangladesh"));
		countryRepository.save(new Country("Barbados"));
		countryRepository.save(new Country("Belarus"));
		countryRepository.save(new Country("Belgium"));
		countryRepository.save(new Country("Belize"));
		countryRepository.save(new Country("Benin"));
		countryRepository.save(new Country("Bermuda"));
		countryRepository.save(new Country("Bhutan"));
		countryRepository.save(new Country("Bolivia"));
		countryRepository.save(new Country("Bosnia and Herzegowina"));
		countryRepository.save(new Country("Botswana"));
		countryRepository.save(new Country("Bouvet Island"));
		countryRepository.save(new Country("Brazil"));
		countryRepository.save(new Country("British Indian Ocean Territory"));
		countryRepository.save(new Country("Brunei Darussalam"));
		countryRepository.save(new Country("Bulgaria"));
		countryRepository.save(new Country("Burkina Faso"));
		countryRepository.save(new Country("Burundi"));
		countryRepository.save(new Country("Cambodia"));
		countryRepository.save(new Country("Cameroon"));
		countryRepository.save(new Country("Canada"));
		countryRepository.save(new Country("Cape Verde"));
		countryRepository.save(new Country("Cayman Islands"));
		countryRepository.save(new Country("Central African Republic"));
		countryRepository.save(new Country("Chad"));
		countryRepository.save(new Country("Chile"));
		countryRepository.save(new Country("China"));
		countryRepository.save(new Country("Christmas Island"));
		countryRepository.save(new Country("Cocos Islands"));
		countryRepository.save(new Country("Colombia"));
		countryRepository.save(new Country("Comoros"));
		countryRepository.save(new Country("Congo"));
		countryRepository.save(new Country("Congo"));
		countryRepository.save(new Country("Cook Islands"));
		countryRepository.save(new Country("Costa Rica"));
		countryRepository.save(new Country("Cota D'Ivoire"));
		countryRepository.save(new Country("Croatia"));
		countryRepository.save(new Country("Cuba"));
		countryRepository.save(new Country("Cyprus"));
		countryRepository.save(new Country("Czech Republic"));
		countryRepository.save(new Country("Denmark"));
		countryRepository.save(new Country("Djibouti"));
		countryRepository.save(new Country("Dominica"));
		countryRepository.save(new Country("Dominican Republic"));
		countryRepository.save(new Country("East Timor"));
		countryRepository.save(new Country("Ecuador"));
		countryRepository.save(new Country("Egypt"));
		countryRepository.save(new Country("El Salvador"));
		countryRepository.save(new Country("Equatorial Guinea"));
		countryRepository.save(new Country("Eritrea"));
		countryRepository.save(new Country("Estonia"));
		countryRepository.save(new Country("Ethiopia"));
		countryRepository.save(new Country("Falkland Islands"));
		countryRepository.save(new Country("Faroe Islands"));
		countryRepository.save(new Country("Fiji"));
		countryRepository.save(new Country("Finland"));
		countryRepository.save(new Country("France"));
		countryRepository.save(new Country("France, Metropolitan"));
		countryRepository.save(new Country("French Guiana"));
		countryRepository.save(new Country("French Polynesia"));
		countryRepository.save(new Country("French Southern Territories"));
		countryRepository.save(new Country("Gabon"));
		countryRepository.save(new Country("Gambia"));
		countryRepository.save(new Country("Georgia"));
		countryRepository.save(new Country("Germany"));
		countryRepository.save(new Country("Ghana"));
		countryRepository.save(new Country("Gibraltar"));
		countryRepository.save(new Country("Greece"));
		countryRepository.save(new Country("Greenland"));
		countryRepository.save(new Country("Grenada"));
		countryRepository.save(new Country("Guadeloupe"));
		countryRepository.save(new Country("Guam"));
		countryRepository.save(new Country("Guatemala"));
		countryRepository.save(new Country("Guinea"));
		countryRepository.save(new Country("Guinea-Bissa"));
		countryRepository.save(new Country("Guyana"));
		countryRepository.save(new Country("Haiti"));
		countryRepository.save(new Country("Heard and McDonald Islands"));
		countryRepository.save(new Country("Holy See"));
		countryRepository.save(new Country("Honduras"));
		countryRepository.save(new Country("Hong Kong"));
		countryRepository.save(new Country("Hungary"));
		countryRepository.save(new Country("Iceland"));
		countryRepository.save(new Country("India"));
		countryRepository.save(new Country("Indonesia"));
		countryRepository.save(new Country("Iran"));
		countryRepository.save(new Country("Iraq"));
		countryRepository.save(new Country("Ireland"));
		countryRepository.save(new Country("Italy"));
		countryRepository.save(new Country("Jamaica"));
		countryRepository.save(new Country("Japan"));
		countryRepository.save(new Country("Jordan"));
		countryRepository.save(new Country("Kazakhstan"));
		countryRepository.save(new Country("Kenya"));
		countryRepository.save(new Country("Kiribati"));
		countryRepository.save(new Country("Democratic People's Republic of Korea"));
		countryRepository.save(new Country("Korea"));
		countryRepository.save(new Country("Kuwait"));
		countryRepository.save(new Country("Kyrgyzstan"));
		countryRepository.save(new Country("Lao"));
		countryRepository.save(new Country("Latvia"));
		countryRepository.save(new Country("Lebanon"));
		countryRepository.save(new Country("Lesotho"));
		countryRepository.save(new Country("Liberia"));
		countryRepository.save(new Country("Libya"));
		countryRepository.save(new Country("Liechtenstein"));
		countryRepository.save(new Country("Lithuania"));
		countryRepository.save(new Country("Luxembourg"));
		countryRepository.save(new Country("Macau"));
		countryRepository.save(new Country("Macedonia"));

		countryRepository.save(new Country("Madagascar"));
		countryRepository.save(new Country("Malawi"));
		countryRepository.save(new Country("Malaysia"));
		countryRepository.save(new Country("Maldives"));
		countryRepository.save(new Country("Mali"));
		countryRepository.save(new Country("Malta"));
		countryRepository.save(new Country("Marshall Islands"));
		countryRepository.save(new Country("Martinique"));
		countryRepository.save(new Country("Mauritania"));

		countryRepository.save(new Country("Mauritius"));
		countryRepository.save(new Country("Mayotte"));
		countryRepository.save(new Country("Mexico"));
		countryRepository.save(new Country("Micronesia"));
		countryRepository.save(new Country("Moldova"));
		countryRepository.save(new Country("Monaco"));
		countryRepository.save(new Country("Mongolia"));
		countryRepository.save(new Country("Montserrat"));
		countryRepository.save(new Country("Morocco"));

		countryRepository.save(new Country("Mozambique"));
		countryRepository.save(new Country("Myanmar"));
		countryRepository.save(new Country("Namibia"));
		countryRepository.save(new Country("Nauru"));
		countryRepository.save(new Country("Nepal"));
		countryRepository.save(new Country("Netherland"));
		countryRepository.save(new Country("Netherlands Antilles"));
		countryRepository.save(new Country("New Caledonia"));
		countryRepository.save(new Country("New Zealand"));

		countryRepository.save(new Country("Nicaragua"));
		countryRepository.save(new Country("Niger"));
		countryRepository.save(new Country("Nigeria"));
		countryRepository.save(new Country("Niue"));
		countryRepository.save(new Country("Norfolk Island"));
		countryRepository.save(new Country("Northern Mariana Islands"));
		countryRepository.save(new Country("Norway"));
		countryRepository.save(new Country("Oman"));
		countryRepository.save(new Country("Pakistan"));
		countryRepository.save(new Country("Palau"));
		countryRepository.save(new Country("Panama"));
		countryRepository.save(new Country("Papua New Guinea"));
		countryRepository.save(new Country("Paraguay"));
		countryRepository.save(new Country("Peru"));
		countryRepository.save(new Country("Philippines"));
		countryRepository.save(new Country("Pitcairn"));
		countryRepository.save(new Country("Poland"));
		countryRepository.save(new Country("Portugal"));
		countryRepository.save(new Country("Puerto Rico"));
		countryRepository.save(new Country("Qatar"));
		countryRepository.save(new Country("Reunion"));
		countryRepository.save(new Country("Romania"));
		countryRepository.save(new Country("Russia"));
		countryRepository.save(new Country("Rwanda"));
		countryRepository.save(new Country("Saint Kitts and Nevis"));
		countryRepository.save(new Country("Saint LUCIA"));
		countryRepository.save(new Country("Saint Vincent"));
		countryRepository.save(new Country("Samoa"));
		countryRepository.save(new Country("San Marino"));
		countryRepository.save(new Country("Sao Tome and Principe"));
		countryRepository.save(new Country("Saudi Arabia"));
		countryRepository.save(new Country("Senegal"));
		countryRepository.save(new Country("Seychelles"));
		countryRepository.save(new Country("Sierra"));
		countryRepository.save(new Country("Singapore"));
		countryRepository.save(new Country("Slovakia"));
		countryRepository.save(new Country("Slovenia"));
		countryRepository.save(new Country("Solomon Islands"));
		countryRepository.save(new Country("Somalia"));
		countryRepository.save(new Country("South Africa"));
		countryRepository.save(new Country("South Georgia"));
		countryRepository.save(new Country("Spain"));
		countryRepository.save(new Country("SriLanka"));
		countryRepository.save(new Country("St. Helena"));
		countryRepository.save(new Country("St. Pierre and Miguelon"));
		countryRepository.save(new Country("Sudan"));
		countryRepository.save(new Country("Suriname"));
		countryRepository.save(new Country("Svalbard"));
		countryRepository.save(new Country("Swaziland"));
		countryRepository.save(new Country("Sweden"));
		countryRepository.save(new Country("Switzerland"));
		countryRepository.save(new Country("Syria"));
		countryRepository.save(new Country("Taiwan"));
		countryRepository.save(new Country("Tajikistan"));
		countryRepository.save(new Country("Tanzania"));
		countryRepository.save(new Country("Thailand"));
		countryRepository.save(new Country("Togo"));
		countryRepository.save(new Country("Tokelau"));
		countryRepository.save(new Country("Tonga"));
		countryRepository.save(new Country("Trinidad and Tobago"));
		countryRepository.save(new Country("Tunisia"));
		countryRepository.save(new Country("Turkey"));
		countryRepository.save(new Country("Turkmenistan"));
		countryRepository.save(new Country("Turks and Caicos"));
		countryRepository.save(new Country("Tuvalu"));
		countryRepository.save(new Country("Uganda"));
		countryRepository.save(new Country("Ukraine"));
		countryRepository.save(new Country("United Arab Emirates"));
		countryRepository.save(new Country("United Kingdom"));
		countryRepository.save(new Country("United States"));
		countryRepository.save(new Country("United States Minor Outlying Islands"));
		countryRepository.save(new Country("Uruguay"));
		countryRepository.save(new Country("Uzbekistan"));
		countryRepository.save(new Country("Vanuatu"));
		countryRepository.save(new Country("Venezuela"));
		countryRepository.save(new Country("Vietnam"));
		countryRepository.save(new Country("Virgin Islands (British)"));
		countryRepository.save(new Country("Virgin Islands (U.S)"));
		countryRepository.save(new Country("Wallis and Futana Islands"));
		countryRepository.save(new Country("Western Sahara"));
		countryRepository.save(new Country("Yemen"));

		countryRepository.save(new Country("Yugoslavia"));
		countryRepository.save(new Country("Zambia"));
		countryRepository.save(new Country("Zimbabwe"));
		//MemberRepository mem=ctx.getBean(MemberRepository.class);
		//mem.save(new Membre("walid","nasri"));*/
		
	}
/*
	@Override
	public void run(String... arg0) throws Exception {
		// TODO Auto-generated method stub
		countryRepository.save(new Country("Afghanistan"));
		countryRepository.save(new Country("Albania"));
		countryRepository.save(new Country("Algeria"));
		countryRepository.save(new Country("American Samoa"));
		countryRepository.save(new Country("Andorra"));
		countryRepository.save(new Country("Angola"));
		countryRepository.save(new Country("Anguilla"));
		countryRepository.save(new Country("Antarctica"));
		countryRepository.save(new Country("Antigua and Barbuda"));
		countryRepository.save(new Country("Argentina"));
		countryRepository.save(new Country("Armenia"));
		countryRepository.save(new Country("Aruba"));
		countryRepository.save(new Country("Australia"));
		countryRepository.save(new Country("Austria"));
		countryRepository.save(new Country("Azerbaijan"));
		countryRepository.save(new Country("Bahamas"));
		countryRepository.save(new Country("Bahrain"));
		countryRepository.save(new Country("Bangladesh"));
		countryRepository.save(new Country("Barbados"));
		countryRepository.save(new Country("Belarus"));
		countryRepository.save(new Country("Belgium"));
		countryRepository.save(new Country("Belize"));
		countryRepository.save(new Country("Benin"));
		countryRepository.save(new Country("Bermuda"));
		countryRepository.save(new Country("Bhutan"));
		countryRepository.save(new Country("Bolivia"));
		countryRepository.save(new Country("Bosnia and Herzegowina"));
		countryRepository.save(new Country("Botswana"));
		countryRepository.save(new Country("Bouvet Island"));
		countryRepository.save(new Country("Brazil"));
		countryRepository.save(new Country("British Indian Ocean Territory"));
		countryRepository.save(new Country("Brunei Darussalam"));
		countryRepository.save(new Country("Bulgaria"));
		countryRepository.save(new Country("Burkina Faso"));
		countryRepository.save(new Country("Burundi"));
		countryRepository.save(new Country("Cambodia"));
		countryRepository.save(new Country("Cameroon"));
		countryRepository.save(new Country("Canada"));
		countryRepository.save(new Country("Cape Verde"));
		countryRepository.save(new Country("Cayman Islands"));
		countryRepository.save(new Country("Central African Republic"));
		countryRepository.save(new Country("Chad"));
		countryRepository.save(new Country("Chile"));
		countryRepository.save(new Country("China"));
		countryRepository.save(new Country("Christmas Island"));
		countryRepository.save(new Country("Cocos Islands"));
		countryRepository.save(new Country("Colombia"));
		countryRepository.save(new Country("Comoros"));
		countryRepository.save(new Country("Congo"));
		countryRepository.save(new Country("Congo"));
		countryRepository.save(new Country("Cook Islands"));
		countryRepository.save(new Country("Costa Rica"));
		countryRepository.save(new Country("Cota D'Ivoire"));
		countryRepository.save(new Country("Croatia"));
		countryRepository.save(new Country("Cuba"));
		countryRepository.save(new Country("Cyprus"));
		countryRepository.save(new Country("Czech Republic"));
		countryRepository.save(new Country("Denmark"));
		countryRepository.save(new Country("Djibouti"));
		countryRepository.save(new Country("Dominica"));
		countryRepository.save(new Country("Dominican Republic"));
		countryRepository.save(new Country("East Timor"));
		countryRepository.save(new Country("Ecuador"));
		countryRepository.save(new Country("Egypt"));
		countryRepository.save(new Country("El Salvador"));
		countryRepository.save(new Country("Equatorial Guinea"));
		countryRepository.save(new Country("Eritrea"));
		countryRepository.save(new Country("Estonia"));
		countryRepository.save(new Country("Ethiopia"));
		countryRepository.save(new Country("Falkland Islands"));
		countryRepository.save(new Country("Faroe Islands"));
		countryRepository.save(new Country("Fiji"));
		countryRepository.save(new Country("Finland"));
		countryRepository.save(new Country("France"));
		countryRepository.save(new Country("France, Metropolitan"));
		countryRepository.save(new Country("French Guiana"));
		countryRepository.save(new Country("French Polynesia"));
		countryRepository.save(new Country("French Southern Territories"));
		countryRepository.save(new Country("Gabon"));
		countryRepository.save(new Country("Gambia"));
		countryRepository.save(new Country("Georgia"));
		countryRepository.save(new Country("Germany"));
		countryRepository.save(new Country("Ghana"));
		countryRepository.save(new Country("Gibraltar"));
		countryRepository.save(new Country("Greece"));
		countryRepository.save(new Country("Greenland"));
		countryRepository.save(new Country("Grenada"));
		countryRepository.save(new Country("Guadeloupe"));
		countryRepository.save(new Country("Guam"));
		countryRepository.save(new Country("Guatemala"));
		countryRepository.save(new Country("Guinea"));
		countryRepository.save(new Country("Guinea-Bissa"));
		countryRepository.save(new Country("Guyana"));
		countryRepository.save(new Country("Haiti"));
		countryRepository.save(new Country("Heard and McDonald Islands"));
		countryRepository.save(new Country("Holy See"));
		countryRepository.save(new Country("Honduras"));
		countryRepository.save(new Country("Hong Kong"));
		countryRepository.save(new Country("Hungary"));
		countryRepository.save(new Country("Iceland"));
		countryRepository.save(new Country("India"));
		countryRepository.save(new Country("Indonesia"));
		countryRepository.save(new Country("Iran"));
		countryRepository.save(new Country("Iraq"));
		countryRepository.save(new Country("Ireland"));
		countryRepository.save(new Country("Italy"));
		countryRepository.save(new Country("Jamaica"));
		countryRepository.save(new Country("Japan"));
		countryRepository.save(new Country("Jordan"));
		countryRepository.save(new Country("Kazakhstan"));
		countryRepository.save(new Country("Kenya"));
		countryRepository.save(new Country("Kiribati"));
		countryRepository.save(new Country("Democratic People's Republic of Korea"));
		countryRepository.save(new Country("Korea"));
		countryRepository.save(new Country("Kuwait"));
		countryRepository.save(new Country("Kyrgyzstan"));
		countryRepository.save(new Country("Lao"));
		countryRepository.save(new Country("Latvia"));
		countryRepository.save(new Country("Lebanon"));
		countryRepository.save(new Country("Lesotho"));
		countryRepository.save(new Country("Liberia"));
		countryRepository.save(new Country("Libya"));
		countryRepository.save(new Country("Liechtenstein"));
		countryRepository.save(new Country("Lithuania"));
		countryRepository.save(new Country("Luxembourg"));
		countryRepository.save(new Country("Macau"));
		countryRepository.save(new Country("Macedonia"));

		countryRepository.save(new Country("Madagascar"));
		countryRepository.save(new Country("Malawi"));
		countryRepository.save(new Country("Malaysia"));
		countryRepository.save(new Country("Maldives"));
		countryRepository.save(new Country("Mali"));
		countryRepository.save(new Country("Malta"));
		countryRepository.save(new Country("Marshall Islands"));
		countryRepository.save(new Country("Martinique"));
		countryRepository.save(new Country("Mauritania"));

		countryRepository.save(new Country("Mauritius"));
		countryRepository.save(new Country("Mayotte"));
		countryRepository.save(new Country("Mexico"));
		countryRepository.save(new Country("Micronesia"));
		countryRepository.save(new Country("Moldova"));
		countryRepository.save(new Country("Monaco"));
		countryRepository.save(new Country("Mongolia"));
		countryRepository.save(new Country("Montserrat"));
		countryRepository.save(new Country("Morocco"));

		countryRepository.save(new Country("Mozambique"));
		countryRepository.save(new Country("Myanmar"));
		countryRepository.save(new Country("Namibia"));
		countryRepository.save(new Country("Nauru"));
		countryRepository.save(new Country("Nepal"));
		countryRepository.save(new Country("Netherland"));
		countryRepository.save(new Country("Netherlands Antilles"));
		countryRepository.save(new Country("New Caledonia"));
		countryRepository.save(new Country("New Zealand"));

		countryRepository.save(new Country("Nicaragua"));
		countryRepository.save(new Country("Niger"));
		countryRepository.save(new Country("Nigeria"));
		countryRepository.save(new Country("Niue"));
		countryRepository.save(new Country("Norfolk Island"));
		countryRepository.save(new Country("Northern Mariana Islands"));
		countryRepository.save(new Country("Norway"));
		countryRepository.save(new Country("Oman"));
		countryRepository.save(new Country("Pakistan"));
		countryRepository.save(new Country("Palau"));
		countryRepository.save(new Country("Panama"));
		countryRepository.save(new Country("Papua New Guinea"));
		countryRepository.save(new Country("Paraguay"));
		countryRepository.save(new Country("Peru"));
		countryRepository.save(new Country("Philippines"));
		countryRepository.save(new Country("Pitcairn"));
		countryRepository.save(new Country("Poland"));
		countryRepository.save(new Country("Portugal"));
		countryRepository.save(new Country("Puerto Rico"));
		countryRepository.save(new Country("Qatar"));
		countryRepository.save(new Country("Reunion"));
		countryRepository.save(new Country("Romania"));
		countryRepository.save(new Country("Russia"));
		countryRepository.save(new Country("Rwanda"));
		countryRepository.save(new Country("Saint Kitts and Nevis"));
		countryRepository.save(new Country("Saint LUCIA"));
		countryRepository.save(new Country("Saint Vincent"));
		countryRepository.save(new Country("Samoa"));
		countryRepository.save(new Country("San Marino"));
		countryRepository.save(new Country("Sao Tome and Principe"));
		countryRepository.save(new Country("Saudi Arabia"));
		countryRepository.save(new Country("Senegal"));
		countryRepository.save(new Country("Seychelles"));
		countryRepository.save(new Country("Sierra"));
		countryRepository.save(new Country("Singapore"));
		countryRepository.save(new Country("Slovakia"));
		countryRepository.save(new Country("Slovenia"));
		countryRepository.save(new Country("Solomon Islands"));
		countryRepository.save(new Country("Somalia"));
		countryRepository.save(new Country("South Africa"));
		countryRepository.save(new Country("South Georgia"));
		countryRepository.save(new Country("Spain"));
		countryRepository.save(new Country("SriLanka"));
		countryRepository.save(new Country("St. Helena"));
		countryRepository.save(new Country("St. Pierre and Miguelon"));
		countryRepository.save(new Country("Sudan"));
		countryRepository.save(new Country("Suriname"));
		countryRepository.save(new Country("Svalbard"));
		countryRepository.save(new Country("Swaziland"));
		countryRepository.save(new Country("Sweden"));
		countryRepository.save(new Country("Switzerland"));
		countryRepository.save(new Country("Syria"));
		countryRepository.save(new Country("Taiwan"));
		countryRepository.save(new Country("Tajikistan"));
		countryRepository.save(new Country("Tanzania"));
		countryRepository.save(new Country("Thailand"));
		countryRepository.save(new Country("Togo"));
		countryRepository.save(new Country("Tokelau"));
		countryRepository.save(new Country("Tonga"));
		countryRepository.save(new Country("Trinidad and Tobago"));
		countryRepository.save(new Country("Tunisia"));
		countryRepository.save(new Country("Turkey"));
		countryRepository.save(new Country("Turkmenistan"));
		countryRepository.save(new Country("Turks and Caicos"));
		countryRepository.save(new Country("Tuvalu"));
		countryRepository.save(new Country("Uganda"));
		countryRepository.save(new Country("Ukraine"));
		countryRepository.save(new Country("United Arab Emirates"));
		countryRepository.save(new Country("United Kingdom"));
		countryRepository.save(new Country("United States"));
		countryRepository.save(new Country("United States Minor Outlying Islands"));
		countryRepository.save(new Country("Uruguay"));
		countryRepository.save(new Country("Uzbekistan"));
		countryRepository.save(new Country("Vanuatu"));
		countryRepository.save(new Country("Venezuela"));
		countryRepository.save(new Country("Vietnam"));
		countryRepository.save(new Country("Virgin Islands (British)"));
		countryRepository.save(new Country("Virgin Islands (U.S)"));
		countryRepository.save(new Country("Wallis and Futana Islands"));
		countryRepository.save(new Country("Western Sahara"));
		countryRepository.save(new Country("Yemen"));

		countryRepository.save(new Country("Yugoslavia"));
		countryRepository.save(new Country("Zambia"));
		countryRepository.save(new Country("Zimbabwe"));
	
		}*/
		
		
	
	
	
}
